const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const base = 'http://localhost:8098';
const userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36';
const { execFileSync } = require('node:child_process');
const seeded = JSON.parse(execFileSync('docker', ['compose', 'run', '--rm', 'cli', 'wp', 'eval-file', 'wp-content/plugins/builder-ab-testing/scripts/builders-demo.php'], { encoding: 'utf8' }));
const demos = Object.entries(seeded).map(([name, demo]) => ({ name, id: demo.experiment, page: demo.page }));
const gutenberg = demos.find((demo) => demo.name === 'gutenberg');
(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const home = await browser.newPage({ userAgent });
    const markup = await (await fetch(base + '/')).text();
    const experiment = JSON.parse(markup.match(/window.BAT_CONFIG=(.*?);/)[1]).experiments[0];
    await home.goto(base + '/');
    await home.waitForURL((url) => [experiment.a, experiment.b].includes(url.href));
    console.log('PASS: homepage routes to assigned variant');
    await home.close();
    for (const variant of ['a', 'b']) {
      const context = await browser.newContext({ userAgent });
      let assignment;
      for (let attempt = 0; attempt < 50; attempt++) {
        const response = await context.request.post(base + '/?rest_route=/builder-ab/v1/assign', { data: { id: experiment.id } });
        assert.equal(response.status(), 200);
        assignment = await response.json();
        if (assignment.variant === variant) break;
      }
      assert.equal(assignment.variant, variant);
      await context.addInitScript(({ experiment, assignment }) => {
        const key = `bat:${experiment.id}:${experiment.revision}`;
        if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(assignment));
      }, { experiment, assignment });
      const page = await context.newPage();
      const eventResponse = (type) => page.waitForResponse((response) => response.url().includes('/event') && response.request().postDataJSON()?.type === type);
      const exposure = eventResponse('exposure');
      await page.goto(base + '/?utm_source=builder-test&gclid=demo&unrelated=discard');
      await page.waitForURL((url) => url.href.startsWith(experiment[variant]));
      assert.equal((await (await exposure).json()).recorded, true);
      assert.equal(new URL(page.url()).searchParams.get('utm_source'), 'builder-test');
      assert.equal(new URL(page.url()).searchParams.get('gclid'), 'demo');
      assert.equal(new URL(page.url()).searchParams.has('unrelated'), false);
      const duplicate = eventResponse('exposure');
      await page.reload();
      assert.equal((await (await duplicate).json()).recorded, false);
      const conversion = eventResponse('conversion');
      await page.getByRole('link', { name: 'Me interesa', exact: true }).click();
      assert.equal((await (await conversion).json()).recorded, true);
      await page.waitForURL(experiment.thankYou);
      const stored = await page.evaluate((experiment) => JSON.parse(localStorage.getItem(`bat:${experiment.id}:${experiment.revision}`)), experiment);
      assert.equal(stored.token, assignment.token);
      console.log(`PASS: full-page ${variant.toUpperCase()} preserves assignment and campaign parameters, deduplicates reloads and records thank-you conversion`);
      await context.close();
    }
    const editorContext = await browser.newContext({ userAgent });
    const editorProbe = await editorContext.newPage();
    let editorRequests = 0;
    editorProbe.on('request', (request) => { if (/\/(assign|event)(?:\?|$)/.test(request.url())) editorRequests++; });
    await editorProbe.goto(base + '/?bricks=run');
    assert.equal(editorProbe.url(), base + '/?bricks=run');
    assert.equal(await editorProbe.evaluate(() => window.BAT_CONFIG), undefined);
    assert.equal(await editorProbe.evaluate(() => localStorage.length), 0);
    assert.equal(editorRequests, 0);
    console.log('PASS: Bricks editor query excludes assignment, redirects, storage and measurements (theme not installed)');
    await editorContext.close();
    for (const demo of demos) {
      for (const variant of ['a', 'b']) {
        const context = await browser.newContext({ userAgent });
        let assignment;
        for (let attempt = 0; attempt < 50; attempt++) {
          const response = await context.request.post(base + '/?rest_route=/builder-ab/v1/assign', { data: { id: demo.id } });
          assert.equal(response.status(), 200);
          assignment = await response.json();
          if (assignment.variant === variant) break;
        }
        assert.equal(assignment.variant, variant);
        await context.addInitScript(({ id, assignment }) => {
          localStorage.setItem(`bat:${id}:1`, JSON.stringify(assignment));
        }, { id: demo.id, assignment });
        const page = await context.newPage();
        const errors = [];
        page.on('pageerror', (error) => errors.push(error.message));
        const exposure = page.waitForResponse((response) => response.url().includes('/event') && response.request().postDataJSON()?.type === 'exposure');
        await page.goto(base + '/?page_id=' + demo.page);
        const selected = page.locator(`[data-bat-experiment="${demo.id}"][data-bat-variant="${variant}"]`);
        const other = page.locator(`[data-bat-experiment="${demo.id}"][data-bat-variant="${variant === 'a' ? 'b' : 'a'}"]`);
        await selected.waitFor({ state: 'visible' });
        assert.equal(await other.isVisible(), false);
        assert.equal((await exposure).status(), 200);
        const conversion = page.waitForResponse((response) => response.url().includes('/event') && response.request().postDataJSON()?.type === 'conversion');
        await selected.getByRole(demo.name === 'atomic' ? 'button' : 'link', { name: 'Me interesa' }).click();
        const result = await conversion;
        assert.equal(result.status(), 200);
        assert.equal((await result.json()).recorded, true);
        assert.equal(errors.length, 0, errors.join('\n'));
        assert.ok(page.url().includes('page_id=' + demo.page));
        console.log(`PASS: ${demo.name} ${variant.toUpperCase()} visible, other variant hidden, exposure and conversion recorded without redirect`);
        await context.close();
      }
      const fallback = await browser.newContext({ javaScriptEnabled: false, userAgent });
      const page = await fallback.newPage();
      await page.goto(base + '/?page_id=' + demo.page);
      assert.equal(await page.locator(`[data-bat-experiment="${demo.id}"][data-bat-variant="a"]`).isVisible(), true);
      assert.equal(await page.locator(`[data-bat-experiment="${demo.id}"][data-bat-variant="b"]`).isVisible(), false);
      console.log(`PASS: ${demo.name} retains A fallback without JavaScript`);
      await fallback.close();
    }
    const deferred = await browser.newContext({ userAgent });
    await deferred.route('**/*', async (route) => {
      if (route.request().resourceType() !== 'document' || !route.request().url().includes('page_id=' + gutenberg.page)) return route.continue();
      const response = await route.fetch();
      const body = (await response.text()).replace(new RegExp(`<div(?=[^>]*data-bat-experiment="${gutenberg.id}")`), '<div style="height:3000px"></div><div');
      await route.fulfill({ response, body });
    });
    const belowFold = await deferred.newPage();
    let exposures = 0;
    belowFold.on('request', (request) => { if (request.url().includes('/event') && request.postDataJSON()?.type === 'exposure') exposures++; });
    await belowFold.goto(base + '/?page_id=' + gutenberg.page);
    await belowFold.waitForFunction((id) => localStorage.getItem(`bat:${id}:1`), gutenberg.id);
    await belowFold.waitForTimeout(100);
    assert.equal(exposures, 0);
    const observed = belowFold.waitForResponse((response) => response.url().includes('/event') && response.request().postDataJSON()?.type === 'exposure');
    await belowFold.locator(`[data-bat-experiment="${gutenberg.id}"]:not([hidden])`).scrollIntoViewIfNeeded();
    assert.equal((await observed).status(), 200);
    console.log('PASS: offscreen element is counted only after entering the viewport');
    await deferred.close();
    const consentContext = await browser.newContext({ userAgent });
    await consentContext.route('**/*', async (route) => {
      if (route.request().resourceType() !== 'document' || !route.request().url().includes('page_id=' + gutenberg.page)) return route.continue();
      const response = await route.fetch();
      await route.fulfill({ response, body: (await response.text()).replace('"consent":false', '"consent":true') });
    });
    const consentPage = await consentContext.newPage();
    await consentPage.goto(base + '/?page_id=' + gutenberg.page);
    assert.equal(await consentPage.evaluate(() => localStorage.length), 0);
    assert.equal(await consentPage.locator('[data-bat-variant="a"]').isVisible(), true);
    const consentAssignment = consentPage.waitForResponse((response) => response.url().includes('/assign'));
    await consentPage.evaluate(() => { window.BAT_CONSENT = true; window.dispatchEvent(new Event('bat:consent')); });
    const granted = await (await consentAssignment).json();
    await consentPage.locator(`[data-bat-variant="${granted.variant}"]`).waitFor({ state: 'visible' });
    await consentPage.evaluate(() => { window.BAT_CONSENT = false; window.dispatchEvent(new Event('bat:consent')); });
    assert.equal(await consentPage.evaluate(() => localStorage.length), 0);
    assert.equal(await consentPage.locator('[data-bat-variant="a"]').isVisible(), true);
    assert.equal(await consentPage.locator('[data-bat-variant="b"]').isVisible(), false);
    console.log('PASS: element consent gates storage and revocation restores A');
    await consentContext.close();
    const admin = await browser.newPage({ userAgent });
    await admin.goto(base + '/wp-login.php');
    await admin.getByLabel('Username or Email Address').fill('batadmin');
    await admin.getByLabel('Password', { exact: true }).fill('bat-local-development');
    await admin.getByRole('button', { name: 'Log In', exact: true }).click();
    await admin.waitForURL(/wp-admin/);
    await admin.goto(base + '/wp-admin/admin.php?page=builder-ab');
    await admin.locator('.bat-experiment').first().waitFor();
    assert.equal(await admin.locator('.bat-kpi').count(), 4);
    const cardCount = await admin.locator('.bat-experiment').count();
    await admin.getByLabel('Buscar experimentos', { exact: true }).fill('gutenberg');
    assert.equal(await admin.locator('.bat-experiment:visible').count(), 1);
    await admin.getByLabel('Buscar experimentos', { exact: true }).fill('no-such-experiment');
    assert.equal(await admin.locator('.bat-experiment:visible').count(), 0);
    assert.equal(await admin.locator('#bat-no-results').isVisible(), true);
    await admin.getByLabel('Buscar experimentos', { exact: true }).fill('');
    assert.equal(await admin.locator('.bat-experiment:visible').count(), cardCount);
    await admin.getByLabel('Filtrar por estado', { exact: true }).selectOption('active');
    assert.equal(await admin.locator('.bat-experiment:visible:not([data-bat-status="active"])').count(), 0);
    await admin.getByLabel('Filtrar por estado', { exact: true }).selectOption('all');
    await admin.setViewportSize({ width: 1440, height: 1000 });
    await admin.screenshot({ path: '.local/admin-desktop.png' });
    await admin.setViewportSize({ width: 390, height: 844 });
    assert.equal(await admin.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await admin.screenshot({ path: '.local/admin-mobile.png' });
    await admin.setViewportSize({ width: 1440, height: 1000 });
    console.log('PASS: dashboard summary, search, status filter, empty state and mobile layout');
    await admin.goto(base + '/wp-admin/admin.php?page=builder-ab&edit=' + gutenberg.id);
    assert.equal(await admin.locator('#bat-mode').inputValue(), 'elements');
    assert.equal(await admin.locator('#bat-a').isVisible(), false);
    assert.equal(await admin.locator('#bat-selector').isVisible(), true);
    await admin.getByRole('button', { name: 'Guardar experimento' }).click();
    await admin.waitForURL(/saved=1/);
    assert.equal(await admin.locator('#bat-mode').inputValue(), 'elements');
    console.log('PASS: admin form saves element mode and hides page-only fields');
    await admin.goto(base + '/wp-admin/post.php?post=' + gutenberg.page + '&action=edit');
    await admin.waitForFunction(() => window.wp?.data?.select('core/block-editor')?.getBlocks().length > 0);
    const blocks = await admin.evaluate(() => wp.data.select('core/block-editor').getBlocks().map((block) => ({ name: block.name, valid: block.isValid })));
    assert.equal(blocks.filter((block) => block.name === 'builder-ab/variant').length, 2);
    assert.ok(blocks.every((block) => block.valid));
    await admin.evaluate(() => wp.data.dispatch('core/block-editor').selectBlock(wp.data.select('core/block-editor').getBlocks()[0].clientId));
    await admin.getByLabel('ID del experimento', { exact: true }).waitFor();
    assert.equal(await admin.getByLabel('ID del experimento', { exact: true }).inputValue(), String(gutenberg.id));
    console.log('PASS: Gutenberg editor loads valid saved blocks and native inspector controls');
    const elementor = demos.find((demo) => demo.name === 'elementor');
    await admin.goto(base + '/wp-admin/post.php?post=' + elementor.page + '&action=elementor');
    await admin.waitForFunction(() => window.elementor?.loaded === true);
    await admin.locator('#elementor-preview-loading').waitFor({ state: 'hidden' });
    await admin.frameLocator('#elementor-preview-iframe').locator('[data-id="bata002"]').click();
    await admin.locator('.elementor-tab-control-advanced').click();
    await admin.getByText('A/B Testing', { exact: true }).click();
    await admin.locator('.elementor-control-_bat_experiment input').waitFor({ state: 'visible' });
    assert.equal(await admin.locator('.elementor-control-_bat_experiment input').inputValue(), '0');
    assert.equal(await admin.locator('.elementor-control-_bat_variant select').isVisible(), true);
    console.log('PASS: Elementor editor exposes native experiment and variant controls');
    const atomic = demos.find((demo) => demo.name === 'atomic');
    await admin.goto(base + '/wp-admin/post.php?post=' + atomic.page + '&action=elementor');
    await admin.waitForFunction(() => window.elementor?.loaded === true);
    await admin.locator('#elementor-preview-loading').waitFor({ state: 'hidden' });
    await admin.frameLocator('#elementor-preview-iframe').locator('[data-id="bata002"]').click();
    await admin.getByText('A/B Testing', { exact: true }).click();
    const atomicId = admin.getByText('ID del experimento', { exact: true }).locator('..').locator('..').locator('input[type="number"]');
    await atomicId.waitFor({ state: 'visible' });
    assert.equal(await atomicId.inputValue(), '0');
    await admin.getByText('Contar clics en este elemento', { exact: true }).waitFor({ state: 'visible' });
    console.log('PASS: Atomic Elements editor exposes native experiment and conversion controls');
    await admin.close();
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
